[package]
name = "desk"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "migrate",
] }
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
